flask_fileupload/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired
from flask_wtf.file import FileRequired, FileField


class UploadForm(FlaskForm):

    upload_name = StringField('Name', validators=[DataRequired()])
    upload_img = FileField(validators=[FileRequired()])

flask_fileupload/__init__.py
from .engine import FlaskFileUpload

flask_fileupload/views.py
from flask import Blueprint, render_template, flash, redirect, request, url_for, jsonify
from .forms import UploadForm
from .storage import StorageNotAllowed, StorageExists, StorageNotExists
from flask_login import login_required


def create_blueprint(import_name, app, storage):

    bp = Blueprint("flask_fileupload", import_name,
                   template_folder="templates",
                   static_folder="static",
                   static_url_path="/static",
                   )

    @bp.route("/", methods=["GET", "POST"])
    @login_required
    def upload():
        form = UploadForm()
        if form.validate_on_submit():
            try:
                filename = storage.store(form.upload_name.data, form.upload_img.data)
            except (StorageNotAllowed, StorageExists) as e:
                flash(str(e), category="danger")
                return redirect(request.url)
            else:
                flash("Image saved: " + filename, category="info")

            return redirect(request.url)

        f = request.files.keys()[0]
        if len(f) > 0:
            try:
                fname = request.files[f].filename
                fdata = request.files[f]
                filename = storage.store(fname, fdata)
            except (StorageNotAllowed, StorageExists) as e:
                ret = {"success":0, "message":str(e), "url":""}
                return jsonify(ret)

            url = '/static/upload/'+filename
            ret = {"success":1, "message":"upload done", "url":url}
            return jsonify(ret)

        return render_template("fileupload/upload.html", form=form)

    @bp.route("/delete/<filename>", methods=["GET"])
    @login_required
    def upload_delete(filename):
        try:
            storage.delete(filename)
            flash("File removed: " + filename, category="info")
        except StorageNotExists as e:
            flash(str(e))

        return redirect(url_for("flask_fileupload.upload"))

    return bp

flask_fileupload/templates/fileupload/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet"/>
    <style>
        body { padding-top: 80px;}
    </style>
    {% block extrastyle %}
    {% endblock %}
</head>
<body>
    <!-- main content -->
     <div class="container">
         {% block message %}
             {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                        <div id="alert_div" class="alert alert-{{category}} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                        </div>
                     </div>
                    {% endfor %}
                {% endif %}
             {% endwith %}
         {% endblock %}

         {% block main %}
         {% endblock main %}

     </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script>
    $(document).ready(function(){
        $("#alert_div").fadeTo(2000, 500).slideUp(500, function(){
            $("#alert_div").slideUp(500);
        });
    });
    </script>

    {% block extrajs %}
    {% endblock %}
</body>
</html>

flask_fileupload/templates/fileupload/upload.html
{% extends 'fileupload/base.html' %}

{% block extrastyle %}
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
    <link href="{{ url_for('flask_fileupload.static', filename='css/zoom.css') }}" rel="stylesheet"/>
{% endblock %}

{% block main %}
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Do you really want to delete this image? It can't be undone.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok">Delete</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>Upload Images</h1>
        </div>
    </div>
    <div class="row">
        <form method="post" enctype=multipart/form-data>
            <div class="form-group">
                {{ form.csrf_token }}
                {{ form.upload_name(required=True, class_="form-control", placeholder=config.FILEUPLOAD_ALLOWED_EXTENSIONS|join(", ")) }}
                {{ form.upload_img }}
                <input class="btn btn-primary pull-right" type="submit" value="Submit">
            </div>
        </form>
        <div class="col-md-12" style="height:30px;"></div>
    </div>
    <hr>
    <div class="row">
        <table id="imges" class="table table-striped table-condensed">
            <thead>
                <tr><th>Name</th><th>Path</th><th>Preview</th><th>Del</th></tr>
            </thead>
            <tbody>
                {% for file_abs in fu_get_existing_files() %}
                    {% set filename = file_abs|fu_filename %}
                    <tr>
                        <td class="col-md-6"><a href="{{ file_abs }}">{{ file_abs|fu_filename }}</a></td>
                        <td class="col-md-4 path-input-col"><input class="path-input" title="path" style="width: 100%;" type="text" readonly value="{{file_abs}}"></td>
                        <td class="col-md-1"><img class="thumbnail zoom" style="height: 30px; width: auto; max-width:30px;" src="{{file_abs}}"> </td>
                        <td class="col-md-1"><a data-href="{{ url_for('flask_fileupload.upload_delete', filename=filename) }}" data-toggle="modal" data-target="#confirm-delete"><span role="button" class="glyphicon glyphicon-trash"></span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block extrajs %}
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            // Build the whole data table
            $('#imges').DataTable({
                "columnDefs":[
                    {"orderable": false, "targets": [1, 2, 3]}
                ]
            });

            // Register autofill on new selected image upload
            document.getElementById("upload_img").addEventListener("change", function(){
                var file = document.getElementById("upload_img").files[0].name;
                {% if config.FILEUPLOAD_RANDOM_FILE_APPENDIX %}
                    var position = file.lastIndexOf(".");
                    var hash = ["_", Math.random().toString(36).substring(6)].join("");
                    file = [file.slice(0, position), hash, file.slice(position)].join("");
                {% endif %}
                document.getElementById("upload_name").value = file
            });

            // Select all on click
            [].forEach.call(document.getElementsByClassName("path-input"), function(input){
                input.addEventListener("click", function(){
                    input.select()
                });
            })
        } );
    </script>

    <script>
        $('#confirm-delete').on('show.bs.modal', function(e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
        });
    </script>
{% endblock extrajs %}